"""Shared FastAPI dependencies."""

from __future__ import annotations

import uuid
from typing import Annotated

from fastapi import Depends, Header
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_session
from app.core.exceptions import ValidationError

SessionDep = Annotated[AsyncSession, Depends(get_session)]


async def get_device_id(
    x_device_id: Annotated[
        str,
        Header(alias="X-Device-Id", description="Stable UUID generated by the client"),
    ],
) -> str:
    try:
        uuid.UUID(x_device_id)
    except (ValueError, AttributeError) as exc:
        raise ValidationError("X-Device-Id header must be a valid UUID") from exc
    return x_device_id


DeviceDep = Annotated[str, Depends(get_device_id)]
